import "@c/styles/globals.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="w-screen flex flex-row">
          <div className="w-2/12">
            <div>Home</div>
            <div>Settings</div>
          </div>
          <div className="w-10/12">
            <div className="h-10">Mentimeter</div>
            <div>{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
